#!/usr/bin/env node
/**
 * pin-badge.mjs — keep the README's "pi pinned" badge in lockstep with the
 * vendored version (#67).
 *
 * The badge is a shields.io *endpoint* badge reading a committed JSON file,
 * so the README markup never changes — only the version inside the JSON does,
 * regenerated from `.sync-state` on every sync. shields renders it because this
 * repo is public; the companion "pi latest" badge reads upstream's releases
 * live, so the two side by side make drift obvious.
 *
 *   node scripts/pin-badge.mjs            # write .github/badges/pi-pinned.json
 *   node scripts/pin-badge.mjs --check    # exit 1 if the file is missing/stale
 *
 * Called by scripts/sync-upstream.sh after it writes .sync-state, and checked
 * in CI so a sync that forgets to regenerate it fails.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const REPO = join(dirname(fileURLToPath(import.meta.url)), "..");
const STATE = join(REPO, ".sync-state");
const OUT = join(REPO, ".github", "badges", "pi-pinned.json");

function pinnedRef() {
	let text;
	try {
		text = readFileSync(STATE, "utf8");
	} catch {
		console.error(`pin-badge: no .sync-state at ${STATE} — run a sync first`);
		process.exit(2);
	}
	const m = /^ref=(.+)$/m.exec(text);
	if (!m) {
		console.error("pin-badge: .sync-state has no ref= line");
		process.exit(2);
	}
	return m[1].trim();
}

function badge(ref) {
	// Endpoint schema: https://shields.io/badges/endpoint-badge
	return { schemaVersion: 1, label: "pi pinned", message: ref, color: "blue" };
}

const ref = pinnedRef();
const desired = `${JSON.stringify(badge(ref), null, 2)}\n`;

if (process.argv.includes("--check")) {
	let current = "";
	try {
		current = readFileSync(OUT, "utf8");
	} catch {
		/* missing */
	}
	if (current !== desired) {
		console.error(
			`pin-badge: ${OUT} is out of date for pinned ref ${ref}.\n` +
				"Run `node scripts/pin-badge.mjs` and commit the result (it is regenerated by scripts/sync-upstream.sh).",
		);
		process.exit(1);
	}
	console.log(`pin-badge: badge matches pinned ref ${ref}`);
} else {
	writeFileSync(OUT, desired);
	console.log(`pin-badge: wrote ${OUT} (pi pinned = ${ref})`);
}
